### ISSUE TITLE
Investigate DBMS

### ISSUE THREAD

**Issue by jeinglis** [agriculture-capstone/agricore#12]

**Comment by ExtraGravity** [comment]
# Database Selection

## RDBMS vs NoSQL

On narrowing down our choices. We are using a RDBMS and not a NoSQL DB. This has already been discussed before. The reasoning is that our data is very relational. For simple storage of say contacts, NoSQL is a good choice due to the reduced complexity and increased speed, but something that involves many parties interacting with one another is a good use case for a RDBMS. https://www.sitepoint.com/sql-vs-nosql-choose/ see scenario 3.

# Selection Criteria

Among RDBMS, we can decide what criteria we think are important.

- Cost
- Cloud Support
- Support
- Functionality
- Security
- Performance
- Portability

## Cost

We need a free solution for now because we don't have funds to pay for anything. This limits us to open source solutions.

Importance 10/10

## Cloud Support

It is likely in the future that we will want to host our DBMS on the cloud. There isn't any particular reason to (because the nature of our product won't need sudden scaling), but for reliability purposes it is also reasonable that a cloud solution will be desired in the future. TL;DR 50/50 chance of being on a cloud in the future. As with Murphy's law, anything that can go wrong will go wrong, we should anticipate a need for this kind of shift in the future, raising the importance.

Importance 7/10

## Support

We do not have a panel of database experts. This means it is important that the DBMS we pick has good community support and is a well explored topic.

Important 9/10

## Functionality

Our application is fairly standard and probably won't be extremely complex, requiring lots of fine tuning and obscure features.

Importance 2/10

## Security

We will possibly be dealing with banking information, this makes security pretty important.

Importance 9/10

## Performance

Because our application is not aimed at a public audience but the amount of users to us is known and not wide spread, there aren't very many performance considerations when picking a DBMS.

Importance 2/10

## Portability

There is no need at the moment to move to any other DBMS in the future, but as with Murphy's law, anything that can go wrong will go wrong, we should anticipate a need for this kind of shift in the future, raising the importance.

Importance 6/10

# Verdict

Based on these requirements, we can say it is important to pick a RDBMS that is free, secure, portable, and popular. Is it not important to pick a very fast DBMS or a highly functional one.

Popular free RDBMS gives limits us to the following choices.

- SQLite
- PostgresSQL
- MySQL

SQLite is ruled out because it can't be supported on the cloud, it also lacks security features as it is an embedded application.

Both Postgres and MySQL are free and open source, they are also both popular and hostable on cloud services. Albeit MySQL is slightly more popular and likely to be available in a hosting solution, but Postgres has a more active community behind it since MySQL was acquired by Oracle.

For portability, Postgres is easier to move to different a DBMS because it is SQL standard compliant. MySQL is not, it will be painful to move MySQL to a different DBMS.

For security, overall security is not just a concern of the DBMS but of the whole stack. Speaking specifically to the DBMS though, Postgres has stronger SSL support compared to MySQL so Postgres comes out a little ahead in this aspect.

## Final Verdict

We should use PostgresSQL because it is:

- Free
- Relational
- Popular
- SQL standard compliant
- Cloud hostable
- Secure

**Comment by Parasrah** [comment]
If we use PostgresSQL we can update the database connection with
```
require('knex')({
  client: 'pg',
  connection: process.env.PG_CONNECTION_STRING,
  searchPath: 'knex,public'
});
```

The docs can be viewed [here](http://knexjs.org/#Installation-client)
