### ISSUE TITLE
Maintenence on Core

### ISSUE THREAD

**Issue by mfalthaw** [agriculture-capstone/agricore#18]
# Description
- Swap to Postgres connector
- Fix a defect with `webpack.definePlugin`
- Swap tests to use `mocha-webpack` like the dashboard
- Swap tests to use `sinon` instead of `testdouble` like other repos
- Swap test to use `expect` instead of `chai` like other 
- Update any packages that are out of date

# Review
@mfalthaw 

# QA
@jeinglis

**Comment by Right2Drive** [comment]
Will make some minor changes while I'm working on this to fix other issues, namely:
- Fix a defect with `webpack.definePlugin`
- Swap tests to use `mocha-webpack` like the dashboard
- Swap tests to use `sinon` instead of `testdouble` like other repos
- Swap test to use `expect` instead of `chai` like other repos

**Comment by Parasrah** [comment]
@agriculture-capstone/developers Widening scope of issue to address some of the issues, please take a look and let me know if you'd prefer I not make any of these changes

**Comment by ExtraGravity** [comment]
We need to assign a reviewer and QA

**Comment by Parasrah** [comment]
Oh you're right it's not defined
